### ISSUE TITLE
Notebook screen blocks the user from running their module 

### ISSUE THREAD

**Issue by develop4learners** [develop4learners/SocialJustice-CS-game#12]
While inside forever loop and the cipher is onscreen AND the notebook is onscreen, the game doesn't take the keystrokes for when the user successfully completes niko_wuz_here_lol hack.  {IDEA: could the problem be a screen within a screen?}

**Comment by develop4learners** [comment]
@spencer6429  By Tuesday, can you re-write Issue #12 to reflect the same format as Issue #8?

**Comment by spencer6429** [comment]
**Documentation of Issue #12**

Testing this bug fix:
1.Keystroke remains lost when cipher is opened
- Problem: users remain stuck once they reach line 181 in a_The_Build_Up.rpy, the ingamemenu is called upon however it freezes the entirety of the game. 
- Desired behavior: Users should be stuck inside the forever loop once check_nikos_hack  is called, and once they change the NIKE_WUZ_HERE_LOL.py, the keystrokes captured will allow the user to advance in the game.
- Testing: Please play until the forever loop for Hack1 and then open the in-game notebook, and then finish Hack1 and you should be able to advance.
-Possible Fix: Calling a screen (line 181,a_The_Build_Up.rpy ) within another screen(line 132, script.rpy) could cause the game to freeze, causing this bug

**Comment by spencer6429** [comment]
Fix: Just utilize the "show" screen instead of a "call" screen when trying to utilize the "screen ingamemenu"
